spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: "@123Mysql"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

jwt:
  secret: ThisIsASecretKeyForJWTThatMustBe32BytesLong!
  expiration: 86400000