spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: "@123Mysql"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true